name: Install dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install wkhtmltopdf
        run: |  
          sudo apt-get install wkhtmltopdf