name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install wkhtmltopdf
        run: |
          sudo apt-get install wkhtmltopdf
      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: coverage run --omit='*dist-packages*' -m pytest test/ -v -s
      - name: Generate Coverage Report
        run: source .envrc && coverage report -m --omit='*dist-packages*' --fail-under=$MIN_COVERAGE